### PR TITLE
Added an API to simplify adding support for some mods

### PR DESCRIPTION
**Pull request by Aang23**
I was recently reported that this wasn't working with UBC (UndergroundBiomesConstruct) in https://github.com/Aang23/UndergroundBiomesConstructs/issues/8 . 
While trying to add support, the only way I could get it working was using reflection. That's not great for something like that.
Those Maps I have implemented here allow the necessary values to be accessed by another mod if their implementation is a bit special.
You can change anything that you want, but, please add some way to do that.

### CODE REVIEW

**Comment by tyra314** [comment]
I also thought about adding an API, so thank you for pushing that on top in my mind. And it looks useful to me, however, I'm not sure if I like it this way. So, if I add an API it should be rather stable in the interface. But this looks a bit limited in functionality. Ás you seem to have a use-case, what are you trying to do?

**Comment by Aang23** [comment]
I am now the main UndergroundBiomesConstruct dev, and, since a little while, modded ores support was added, and the created ores took there Tool, Hardness and Level from the input ore state, which works perfectly. But, recently, someone wanted to use your mod, TooProgression, to change the mining level per stone type, and not by ore. This was evidently not working, and reported to me.
While trying to fix that, I ran into multiples issues :
1) I needed to keep the default behavior (taking the base ore's values), thus breaking your BlockOverwrite methods,
2) After realizing that, I realized that the easiest and cleanest way of doing that would be to simply be able to get those overwritten values from ToolProgression. The only way I could get that to work was using reflection to change _static String getConfigFromState(IBlockState state)_ 's visibility... Worked, but I don't like using reflection when there is a very simple way of avoiding it.
3) After searching for any way to avoid reflection, I came to the conclusion that the best way would be if ToolProgression has an API, so I made this PR with only the necessary for my use case where I need to access 2 things : 
- The BlockOverwrite generated by this same class,
- The modified block list to switch between default ore / overwritten value.

I implemented it that way to keep it simple, but do it as you like it !

**Comment by tyra314** [comment]
For now, I'm adding it like it is, but I won't promise to never change it.

**Comment by tyra314** [comment]
Will be part of the upcoming [v1.5.7](https://minecraft.curseforge.com/projects/tool-progression/files/2636658)

**Comment by Aang23** [comment]
Thanks. Change it as you want.

**Pull request merged**
